"""add new db models

Revision ID: 13bbdb43f3dd
Revises: 
Create Date: 2020-12-21 11:35:16.493583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bbdb43f3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('profile_image', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('property_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.Text(length=64), nullable=False),
    sa.Column('property_desc', sa.Text(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('property_price', sa.Integer(), nullable=False),
    sa.Column('property_location', sa.Text(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property_listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_image')
    op.drop_table('property_listing')
    op.drop_table('User')
    # ### end Alembic commands ###
