"""upgrade property model and user model with new columns

Revision ID: 486bfffc2655
Revises: 158d85d2b812
Create Date: 2021-02-20 18:50:10.263853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486bfffc2655'
down_revision = '158d85d2b812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('condition', sa.String(length=30), default="not specified", nullable=True))
    op.add_column('property', sa.Column('deal_done', sa.Boolean(), default=False, nullable=True))
    op.add_column('property', sa.Column('is_available', sa.Boolean(), default=False, nullable=True))
    op.add_column('property', sa.Column('type', sa.String(length=50), default="other", nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'type')
    op.drop_column('property', 'is_available')
    op.drop_column('property', 'deal_done')
    op.drop_column('property', 'condition')
    # ### end Alembic commands ###
