"""initial migration

Revision ID: 5ecef9206472
Revises: 
Create Date: 2021-03-05 11:51:42.854630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ecef9206472"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("other_name", sa.String(length=30), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("address_1", sa.String(length=100), nullable=False),
        sa.Column("address_2", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("photo", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_vendor", sa.Boolean(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(length=64), nullable=False),
        sa.Column("desc", sa.Text(length=256), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("location", sa.Text(length=64), nullable=False),
        sa.Column("image_folder", sa.Text(), nullable=True),
        sa.Column("photos", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("deal_done", sa.Boolean(), nullable=True),
        sa.Column("condition", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property")
    op.drop_table("token_blacklist")
    op.drop_table("User")
    # ### end Alembic commands ###
